version: '3.9'
services:
    node:
        image: tp2
        environment:
            - NODE_ENV=${NODE_ENV}
        ports:
            -   "3000:3000"
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
volumes:
    db-data: